### ISSUE TITLE
Bug installing on Windows WSL? something missing?

### ISSUE THREAD

**Issue by ozett** [koenvervloesem/humble-explorer#41]
trying to install the explorer in WSL (ubuntu 20.04 LTS, python 3.8).
install went smooth, but on start there are errors.
any hints to overcome this?

![image](https://user-images.githubusercontent.com/5937811/210230760-ff0ca3a8-3d8c-42e3-8153-15f34bd4aef3.png)

**Comment by ozett** [comment]
installing bluez did not help

![image](https://user-images.githubusercontent.com/5937811/210231494-ef8aaeba-a547-4661-b233-2666d4dadf0e.png)

**Comment by ozett** [comment]
installing bluez-tools did not help

![image](https://user-images.githubusercontent.com/5937811/210231668-39f3c246-f026-4956-9ab4-50f6e27e92d1.png)

**Comment by ozett** [comment]
not possible? not in kernel for WSL?

https://www.reddit.com/r/bashonubuntuonwindows/comments/wecdsu/comment/iinxbgz/

**Comment by ozett** [comment]
maybe workaround? too much hassle..

https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/

**Comment by koenvervloesem** [comment]
Thanks for trying this out on a configuration I hadn't thought about! If I'm reading correctly, the most viable approach would be with USB/IP indeed.

Do you really need to run this package on WSL? Why not on the Windows host system?

**Comment by ozett** [comment]
as i am no developer but willing to try my best, 

i simply dont know how to "start" t on python on windows without having an executable.
i have installed visual-studio-code and for platfrom.io there seems somewhere a python win32.

i am in doubt, if that overcomes hardware-access to the bluetooth-devices...

**Comment by koenvervloesem** [comment]
Just install Python from the Microsoft Store on Windows.

Then type `pip install humble-explorer` in a command prompt.

After this, you should be able to run `humble-explorer` in a command prompt.

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/210261358-85081e0b-08de-476c-8ba4-74efec059e09.png)

**Comment by ozett** [comment]
❤️ 

![image](https://user-images.githubusercontent.com/5937811/210261418-72a06a98-98ce-4979-9518-e35b7d0c61ef.png)

**Comment by ozett** [comment]
it scrolling fast, i cannot read anything. 
how to freeze?

**Comment by koenvervloesem** [comment]
Type S for settings and then disable auto-scroll in the sidebar that appears.

**Comment by koenvervloesem** [comment]
Or type T to pause or resume the scan.
