### ISSUE TITLE
[FR] Whats the meaning of the color Coding for TIME an MAC

### ISSUE THREAD

**Issue by ozett** [koenvervloesem/humble-explorer#43]
on fiist glance i found nothing in the docs, maybe i overlooked.
but is there a background to the color-coding of the time and MAC sections?

![image](https://user-images.githubusercontent.com/5937811/210273787-10e93bdb-40b4-487c-8090-2e72bf9fe78d.png)

**Comment by koenvervloesem** [comment]
See https://humble-explorer.readthedocs.io/en/stable/usage.html#user-interface

The colors are to recognize easily which addresses are the same, or to see which timestamps are withing the same second.
